name: Update flake

on:
  schedule:
    - cron: "52 13 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.M15A_GITHUB_PAT }}
          branch: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Update flake lock file
        run: |
          nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'flake.lock'
          commit_message: "auto: update flake lock"
